# Alertmanager
# Kind: Alertmanager, Service, ServiceAccount
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  name: kube-prometheus-stack-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 39.9.0
    chart: kube-prometheus-stack-39.9.0
    heritage: Helm
    release: kube-prometheus-stack
spec:
  externalUrl: http://kube-prometheus-stack-alertmanager.monitoring:9093
  image: quay.io/prometheus/alertmanager:v0.25.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: kube-prometheus-stack-alertmanager
  version: v0.25.0
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/version: "39.9.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-39.9.0
    release: "prometheus-stack"
    heritage: "Helm"
    self-monitor: "true"
spec:
  ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    alertmanager: kube-prometheus-stack-alertmanager
    app.kubernetes.io/name: alertmanager
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus-stack-alertmanager
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-stack-alertmanager
    app.kubernetes.io/part-of: prometheus-stack
    app.kubernetes.io/version: "39.9.0"
    chart: kube-prometheus-stack-39.9.0
    heritage: Helm
    release: "prometheus-stack"
  name: kube-prometheus-stack-alertmanager
  namespace: monitoring
