apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/version: "39.9.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-39.9.0
    release: "prometheus-stack"
    heritage: "Helm"
spec:
  route:
    groupBy: [severity]
#    group_wait: 0s
#    group_interval: 30s
#    repeat_interval: 12h
    receiver: 'slack-notifications'
#    routes:
#    - match:
#        - alertname =~ "InfoInhibitor|Watchdog"
#      receiver: 'slack-notifications'
  receivers:
    - name: 'slack-notifications'
      slackConfigs:
        - apiURL:
            name: my-secret
            key: slack-webhook-url
          username: AlertManager
#        - apiURL: "https://hooks.slack.com/services/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"
        - channel: '#k8s-alert'
          sendResolved: true
          title: '[{{.Status | toUpper}}] {{ .CommonLabels.alertname }}'
          text: |
            *Description:* {{ .CommonAnnotations.description }}
